server:
  port: 7201
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luocaihong/mycloudconfig.git
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672    # RabbitMQ的监听端口
    username: guest  # 用户名
    password: guest # 密码
  application:
    name: mycloud-config-bus
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:87654321@localhost:7301/eureka # 新搭建的eureka模块mycloud-config-eureka，只负责配置中心的注册
  instance:
    prefer-ip-address: true # 在地址栏上使用IP地址进行显示
    instance-id: mycloud-config-bus
management:
  endpoints:
    web:
      exposure:
        include: "*"