server:
  port: 8402
spring:
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                addresses: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
      bindings: # 服务的整合处理
#        input: # 这个名字是一个通道的名称，在分析具体源代码的时候会进行说明，相对于消息来说，consumer是input
        enjoy_input: # 自定义的通道名称，对应mycloud-api模块DefaultProcess.java中定义
          destination: EnjoyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: enjoy_group # group对应rabbitmq中的队列，防止同一个消息被重复消费；不指定group，产生的是匿名队列
      rabbit:
        bindings:
          enjoy_input: # 通道名称
            consumer: # 表示客户端
              bindingRoutingKey: enjoyRoutingKey # 绑定的路由键，默认是#
  application:
    name: mycloud-stream-consumer