server:
  port: 7101
spring:
  application:
    name: mycloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luocaihong/mycloudconfig.git
eureka: # 将配置中心注册到eureka
  client:
    service-url:
      defaultZone: http://admin:87654321@localhost:7301/eureka # 新搭建的eureka模块mycloud-config-eureka，只负责配置中心的注册
#      defaultZone: http://admin:87654321@eureka:7001/eureka,http://admin:87654321@eureka2:7002/eureka,http://admin:87654321@eureka3:7003/eureka # 也可以继续使用原来的eureka
  instance:
    prefer-ip-address: true # 在地址栏上使用IP地址进行显示
    instance-id: microcloud-config