#server:
#  port: 7001
#eureka:
#  instance: # eureka实例定义
#    hostname: eureka # 定义 Eureka 实例所在的主机名称
#  server:
#    eviction-interval-timer-in-ms: 1000 #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
#    enable-self-preservation: false #设置为false表示关闭保护模式
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://admin:87654321@eureka:7001/eureka,http://admin:87654321@eureka2:7002/eureka,http://admin:87654321@eureka3:7003/eureka
#spring:
#  security: #增加用户、密码验证
#    user:
#      name: admin
#      password: 87654321

spring:
  profiles:
    active:
      - dev-7001

---
server:
  port: 7001
eureka:
  instance: # eureka实例定义
    hostname: eureka # 定义 Eureka 实例所在的主机名称
  server:
    eviction-interval-timer-in-ms: 1000 #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
  client:
    fetch-registry: false # 从eureka server拉起注册表信息
    register-with-eureka: false #当前的客户端是否应该注册到erueka中
    service-url:
      defaultZone: http://admin:87654321@eureka:7001/eureka,http://admin:87654321@eureka2:7002/eureka,http://admin:87654321@eureka3:7003/eureka
spring:
  profiles: dev-7001
  security: #增加用户、密码验证
    user:
      name: admin
      password: 87654321
  application:
    name: mycloud-eureka

---
server:
  port: 7002
eureka:
  instance: # eureka实例定义
    hostname: eureka2 # 定义 Eureka 实例所在的主机名称
  server:
    eviction-interval-timer-in-ms: 1000 #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:87654321@eureka:7001/eureka,http://admin:87654321@eureka2:7002/eureka,http://admin:87654321@eureka3:7003/eureka
spring:
  profiles: dev-7002
  security: #增加用户、密码验证
    user:
      name: admin
      password: 87654321
  application:
    name: mycloud-eureka2

---
server:
  port: 7003
eureka:
  instance: # eureka实例定义
    hostname: eureka3 # 定义 Eureka 实例所在的主机名称
  server:
    eviction-interval-timer-in-ms: 1000 #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:87654321@eureka:7001/eureka,http://admin:87654321@eureka2:7002/eureka,http://admin:87654321@eureka3:7003/eureka
spring:
  profiles: dev-7003
  security: #增加用户、密码验证
    user:
      name: admin
      password: 87654321
  application:
    name: mycloud-eureka3