server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:87654321@eureka:7001/eureka,http://admin:87654321@eureka2:7002/eureka,http://admin:87654321@eureka3:7003/eureka
feign:
  compression: # 压缩配置,默认不开启
    request:
      enabled: true
      mime-types: # 可以被压缩的类型
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048 # 超过2048的字节进行压缩
  hystrix:
    enabled: true # 启用hystrix配置
logging: # 默认 Feign的日志是不开启的
  level:
    com.sg.mycloud.service: debug